plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.0'
	id 'io.spring.dependency-management' version '1.1.7'
	id "com.github.davidmc24.gradle.plugin.avro" version "1.5.0"

}
ext {
	springAiVersion = "1.0.0"
}

group = 'com.DongMunSeoDap'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
	maven {
		url 'https://packages.confluent.io/maven/'
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.kafka:spring-kafka'
	compileOnly 'org.projectlombok:lombok'
//	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.kafka:spring-kafka-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation "io.confluent:kafka-avro-serializer:7.5.0"

	implementation platform("software.amazon.awssdk:bom:2.21.10") // BOM으로 버전 통일
	implementation "software.amazon.awssdk:s3"

	// PDF 처리 (Apache PDFBox)
	implementation 'org.apache.pdfbox:pdfbox:3.0.1'
	implementation 'org.apache.pdfbox:pdfbox-tools:3.0.1'
	implementation 'org.apache.pdfbox:fontbox:3.0.1'

	implementation 'org.springframework.ai:spring-ai-starter-vector-store-pinecone'
	implementation 'org.springframework.ai:spring-ai-starter-model-openai'
}

tasks.named('test') {
	useJUnitPlatform()
}

sourceSets {
	main{
		java {
			srcDirs += 'build/generated-main-avro-java'
		}
	}
}
dependencyManagement {
	imports {
		mavenBom "org.springframework.ai:spring-ai-bom:$springAiVersion"
	}
}
