{
  "type": "record",
  "name": "DocumentUploadedEvent",
  "namespace": "com.example.dongmunseodap",
  "fields": [
    { "name": "version", "type": "string" },
    { "name": "event_type", "type": "string" },
    { "name": "trace_id", "type": "string" },
    {
      "name": "payload",
      "type": {
        "type": "record",
        "name": "Payload",
        "fields": [
          { "name": "document_id", "type": "string" },
          { "name": "file_name", "type": "string" },
          { "name": "s3_path", "type": "string" },
          { "name": "uploaded_by", "type": "string" },
          { "name": "uploaded_at",
		        "type": {
                  "type": "long",
                  "logicalType": "timestamp-millis"},
            "doc": "ISO 8601 timestamp" }
        ]
      }
    },
    {
      "name": "meta",
      "type": {
        "type": "record",
        "name": "Meta",
        "fields": [
          { "name": "mime_type", "type": "string" },
          { "name": "language", "type": "string" }
        ]
      }
    }
  ]
}